## This configuration was generated by terraform-provider-oci

resource oci_containerengine_node_pool export_Meow-node-pool {
  cluster_id     = oci_containerengine_cluster.export_Meow-k8s.id
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T01:01:58.309Z"
  }
  freeform_tags = {
  }
  initial_node_labels {
    key   = "name"
    value = "Meow-cluster"
  }
  kubernetes_version = "v1.34.1"
  name               = "Meow-node-pool"
  node_config_details {
    defined_tags = {
    }
    freeform_tags = {
    }
    #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    node_pool_pod_network_option_details {
      cni_type = "FLANNEL_OVERLAY"
      #max_pods_per_node = <<Optional value not found in discovery>>
      #pod_nsg_ids = <<Optional value not found in discovery>>
      #pod_subnet_ids = <<Optional value not found in discovery>>
    }
    nsg_ids = [
    ]
    placement_configs {
      availability_domain = data.oci_identity_availability_domain.export_Ozdw-SA-VINHEDO-1-AD-1.name
      #capacity_reservation_id = <<Optional value not found in discovery>>
      fault_domains = [
      ]
      #preemptible_node_config = <<Optional value not found in discovery>>
      subnet_id = oci_core_subnet.export_Meow-private-subnet.id
    }
    size = "2"
  }
  node_metadata = {
  }
  node_shape = "VM.Standard.A1.Flex"
  node_shape_config {
    memory_in_gbs = "12"
    ocpus         = "2"
  }
  node_source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    image_id    = var.oci_core_instance--source_details-source_id--export_oke-cln3bywbt6q-nkqj4ofskra-s7mzdwsnkaq-1_1
    source_type = "IMAGE"
  }
  #quantity_per_subnet = <<Optional value not found in discovery>>
  ssh_public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjxq7DxDnypH5Im959Tzn39GNL+ScLHAqVCE1/Q9/GxeD30aBRfNlLuUcJqkWSYu3cfZpLoCTcLmdRIUx2bK79TM12vx3d2WLizDEex2+PAI1w9e8qK8QsgoXl8gVXz3lYlJfuapx7AADqQ8P/d1iC9olGsHvA0Vgd0aJgusba5xXESPPtChTM+H31Ljn78qEjb4W6K8YeEQ6Lw/BBhXKd4+/XjnmTm5P6Zh0ELlDgnRv01/ELqPTBoZX274lw5A1k5U/3sJUItDUs0R/ZtOVcnAEdRpTAQTV9F/HtrRzSA8tI1T3pkv5j8bHg5oI8u212zVmbF2AXdEyM3CdUJnlp\n"
  #subnet_ids = <<Optional value not found in discovery>>
}

resource oci_containerengine_cluster export_Meow-k8s {
  cluster_pod_network_options {
    cni_type = "FLANNEL_OVERLAY"
  }
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T00:54:04.424Z"
  }
  endpoint_config {
    is_public_ip_enabled = "false"
    nsg_ids = [
    ]
    subnet_id = oci_core_subnet.export_Meow-public-subnet.id
  }
  freeform_tags = {
  }
  image_policy_config {
    is_policy_enabled = "false"
  }
  #kms_key_id = <<Optional value not found in discovery>>
  kubernetes_version = "v1.34.1"
  name               = "Meow-k8s"
  options {
    add_ons {
      is_kubernetes_dashboard_enabled = "false"
      is_tiller_enabled               = "false"
    }
    admission_controller_options {
      is_pod_security_policy_enabled = "false"
    }
    ip_families = [
      "IPv4",
    ]
    kubernetes_network_config {
      pods_cidr     = "10.244.0.0/16"
      services_cidr = "10.96.0.0/16"
    }
    #open_id_connect_discovery = <<Optional value not found in discovery>>
    #open_id_connect_token_authentication_config = <<Optional value not found in discovery>>
    persistent_volume_config {
      #defined_tags = <<Optional value not found in discovery>>
      freeform_tags = {
      }
    }
    service_lb_config {
      backend_nsg_ids = [
      ]
      #defined_tags = <<Optional value not found in discovery>>
      freeform_tags = {
      }
    }
    service_lb_subnet_ids = [
      oci_core_subnet.export_Meow-public-subnet.id,
    ]
  }
  type   = "BASIC_CLUSTER"
  vcn_id = oci_core_vcn.export_Meow-VCN.id
}

