## This configuration was generated by terraform-provider-oci

resource oci_dns_view export_Meow-VCN_1 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T00:54:00.420Z"
  }
  display_name = "Meow-VCN"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_resolver export_Meow-VCN_2 {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T00:54:00.420Z"
  }
  display_name = "Meow-VCN"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  resolver_id = "ocid1.dnsresolver.oc1.sa-vinhedo-1.amaaaaaau5mmyiaat4fhj7stleitaj3b5aiejlkpexhi3mes6ifzdzthzahq"
  #scope = <<Optional value not found in discovery>>
}

resource oci_dns_zone export_2-10-in-addr-arpa {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T00:54:00.420Z"
  }
  dnssec_state = "DISABLED"
  freeform_tags = {
    "module"      = "oracle-terraform-modules/vcn/oci"
    "terraformed" = "Please do not edit manually"
  }
  name      = "2.10.in-addr.arpa"
  scope     = "PRIVATE"
  view_id   = oci_dns_view.export_Meow-VCN_1.id
  zone_type = "PRIMARY"
}

resource oci_dns_rrset export_2-10-in-addr-arpa_2-10-in--addr-arpa_NS {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "2.10.in-addr.arpa"
  items {
    domain = "2.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com."
    rtype  = "NS"
    ttl    = "86400"
  }
  rtype = "NS"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_2-10-in-addr-arpa.id
}

resource oci_dns_rrset export_2-10-in-addr-arpa_2-10-in--addr-arpa_SOA {
  #compartment_id = <<Optional value not found in discovery>>
  domain = "2.10.in-addr.arpa"
  items {
    domain = "2.10.in-addr.arpa"
    rdata  = "vcn-dns.oraclevcn.com. hostmaster.oracle.com. 1 3600 3600 3600 10"
    rtype  = "SOA"
    ttl    = "86400"
  }
  rtype = "SOA"
  #scope = <<Optional value not found in discovery>>
  #view_id = <<Optional value not found in discovery>>
  zone_name_or_id = oci_dns_zone.export_2-10-in-addr-arpa.id
}

