## This configuration was generated by terraform-provider-oci

resource oci_logging_log_group export_logs {
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T20:29:19.358Z"
  }
  #description = <<Optional value not found in discovery>>
  display_name = "logs"
  freeform_tags = {
  }
}

resource oci_logging_log export_SiteToSiteVPN_read {
  configuration {
    compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
    source {
      category = "read"
      parameters = {
      }
      resource    = oci_core_ipsec.export_SiteToSiteVPN.id
      service     = "oci_c3_vpn"
      source_type = "OCISERVICE"
    }
  }
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-27T20:29:21.867Z"
  }
  display_name = "SiteToSiteVPN_read"
  freeform_tags = {
  }
  is_enabled         = "true"
  log_group_id       = oci_logging_log_group.export_logs.id
  log_type           = "SERVICE"
  retention_duration = "30"
}

