variable "compartment_id" { }
variable "name" { }
variable "vcn_id" { }
variable "drg_id" { }
variable "cpe_name" { }
variable "cpe_public_ip" { }
variable "cpe_network_cidr" { }
variable "cpe_private_ip" { }
variable "vpn_shared_secret" { }
