#!/bin/bash

DIR=${1:-tmp}

mkdir -p $DIR
terraform-provider-oci -command=export -compartment_name=meow -output_path=${DIR}
oci search resource structured-search --query-text "QUERY all resources where lifeCycleState != 'DELETED' &&  lifeCycleState != 'TERMINATED' && lifeCycleState != 'FAILED'" >${DIR}/query_all.json
