## This configuration was generated by terraform-provider-oci

resource oci_artifacts_container_configuration export_container_configuration {
  compartment_id                      = "ocid1.compartment.oc1..aaaaaaaannct6novmzbj6jisye6wc46chyel4bh7kn73y5qfafdzsjfxi2nq"
  is_repository_created_on_first_push = "true"
}

