## This configuration was generated by terraform-provider-oci

resource oci_network_load_balancer_network_load_balancer export_Meow-nlb_1 {
  #assigned_ipv6 = <<Optional value not found in discovery>>
  #assigned_private_ipv4 = <<Optional value not found in discovery>>
  compartment_id = oci_artifacts_container_configuration.export_container_configuration.id
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/ibere@tizio.com.br"
    "Oracle-Tags.CreatedOn" = "2025-12-25T22:08:59.026Z"
  }
  display_name = "Meow-nlb"
  freeform_tags = {
  }
  is_preserve_source_destination = "false"
  is_private                     = "false"
  is_symmetric_hash_enabled      = "false"
  network_security_group_ids = [
  ]
  nlb_ip_version = "IPV4"
  #reserved_ips = <<Optional value not found in discovery>>
  security_attributes = {
  }
  subnet_id = oci_core_subnet.export_Meow-public-subnet.id
  #subnet_ipv6cidr = <<Optional value not found in discovery>>
}

resource oci_network_load_balancer_backend_set export_Meow-backend-set-http {
  are_operationally_active_backends_preferred = "false"
  health_checker {
    #dns = <<Optional value not found in discovery>>
    interval_in_millis = "10000"
    port               = "0"
    protocol           = "TCP"
    request_data       = ""
    #response_body_regex = <<Optional value not found in discovery>>
    response_data = ""
    retries       = "3"
    #return_code = <<Optional value not found in discovery>>
    timeout_in_millis = "3000"
    #url_path = <<Optional value not found in discovery>>
  }
  ip_version                            = "IPV4"
  is_fail_open                          = "false"
  is_instant_failover_enabled           = "false"
  is_instant_failover_tcp_reset_enabled = "true"
  is_preserve_source                    = "false"
  name                                  = "Meow-backend-set-http"
  network_load_balancer_id              = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  policy                                = "FIVE_TUPLE"
}

resource oci_network_load_balancer_backend_set export_Meow-backend-set-https {
  are_operationally_active_backends_preferred = "false"
  health_checker {
    #dns = <<Optional value not found in discovery>>
    interval_in_millis = "10000"
    port               = "0"
    protocol           = "TCP"
    request_data       = ""
    #response_body_regex = <<Optional value not found in discovery>>
    response_data = ""
    retries       = "3"
    #return_code = <<Optional value not found in discovery>>
    timeout_in_millis = "3000"
    #url_path = <<Optional value not found in discovery>>
  }
  ip_version                            = "IPV4"
  is_fail_open                          = "false"
  is_instant_failover_enabled           = "false"
  is_instant_failover_tcp_reset_enabled = "true"
  is_preserve_source                    = "false"
  name                                  = "Meow-backend-set-https"
  network_load_balancer_id              = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  policy                                = "FIVE_TUPLE"
}

resource oci_network_load_balancer_backend export_ocid1-instance-oc1-sa-vinhedo-1-an3ggljru5mmyiacnhnh2wtmt4xk4j6f7bvomxas5ffzvymk53kjmfov7osq-30080 {
  backend_set_name         = oci_network_load_balancer_backend_set.export_Meow-backend-set-http.name
  ip_address               = "10.2.1.74"
  is_backup                = "false"
  is_drain                 = "false"
  is_offline               = "false"
  name                     = "ocid1.instance.oc1.sa-vinhedo-1.an3ggljru5mmyiacnhnh2wtmt4xk4j6f7bvomxas5ffzvymk53kjmfov7osq.30080"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "30080"
  target_id                = oci_core_instance.export_oke-cydfs4cg5ka-n4fgkeqjytq-slrjkpgue2q-1_1.id
  weight                   = "1"
}

resource oci_network_load_balancer_backend export_ocid1-instance-oc1-sa-vinhedo-1-an3ggljru5mmyiacnlpnxd2im75pgb5qctk2nnoi4oacbadzm7dr7ovowhha-30080 {
  backend_set_name         = oci_network_load_balancer_backend_set.export_Meow-backend-set-http.name
  ip_address               = "10.2.1.66"
  is_backup                = "false"
  is_drain                 = "false"
  is_offline               = "false"
  name                     = "ocid1.instance.oc1.sa-vinhedo-1.an3ggljru5mmyiacnlpnxd2im75pgb5qctk2nnoi4oacbadzm7dr7ovowhha.30080"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "30080"
  target_id                = oci_core_instance.export_oke-cydfs4cg5ka-n4fgkeqjytq-slrjkpgue2q-0_1.id
  weight                   = "1"
}

resource oci_network_load_balancer_listener export_Meow-nlb_1_k8s-nlb-listener_http {
  default_backend_set_name = oci_network_load_balancer_backend_set.export_Meow-backend-set-http.name
  ip_version               = "IPV4"
  is_ppv2enabled           = "false"
  #l3ip_idle_timeout = <<Optional value not found in discovery>>
  name                     = "k8s-nlb-listener_http"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "80"
  protocol                 = "TCP"
  tcp_idle_timeout         = "360"
  #udp_idle_timeout = <<Optional value not found in discovery>>
}

resource oci_network_load_balancer_backend export_ocid1-instance-oc1-sa-vinhedo-1-an3ggljru5mmyiacnhnh2wtmt4xk4j6f7bvomxas5ffzvymk53kjmfov7osq-30443 {
  backend_set_name         = oci_network_load_balancer_backend_set.export_Meow-backend-set-https.name
  ip_address               = "10.2.1.74"
  is_backup                = "false"
  is_drain                 = "false"
  is_offline               = "false"
  name                     = "ocid1.instance.oc1.sa-vinhedo-1.an3ggljru5mmyiacnhnh2wtmt4xk4j6f7bvomxas5ffzvymk53kjmfov7osq.30443"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "30443"
  target_id                = oci_core_instance.export_oke-cydfs4cg5ka-n4fgkeqjytq-slrjkpgue2q-1_1.id
  weight                   = "1"
}

resource oci_network_load_balancer_backend export_ocid1-instance-oc1-sa-vinhedo-1-an3ggljru5mmyiacnlpnxd2im75pgb5qctk2nnoi4oacbadzm7dr7ovowhha-30443 {
  backend_set_name         = oci_network_load_balancer_backend_set.export_Meow-backend-set-https.name
  ip_address               = "10.2.1.66"
  is_backup                = "false"
  is_drain                 = "false"
  is_offline               = "false"
  name                     = "ocid1.instance.oc1.sa-vinhedo-1.an3ggljru5mmyiacnlpnxd2im75pgb5qctk2nnoi4oacbadzm7dr7ovowhha.30443"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "30443"
  target_id                = oci_core_instance.export_oke-cydfs4cg5ka-n4fgkeqjytq-slrjkpgue2q-0_1.id
  weight                   = "1"
}

resource oci_network_load_balancer_listener export_Meow-nlb_1_k8s-nlb-listener-https {
  default_backend_set_name = oci_network_load_balancer_backend_set.export_Meow-backend-set-https.name
  ip_version               = "IPV4"
  is_ppv2enabled           = "false"
  #l3ip_idle_timeout = <<Optional value not found in discovery>>
  name                     = "k8s-nlb-listener-https"
  network_load_balancer_id = oci_network_load_balancer_network_load_balancer.export_Meow-nlb_1.id
  port                     = "443"
  protocol                 = "TCP"
  tcp_idle_timeout         = "360"
  #udp_idle_timeout = <<Optional value not found in discovery>>
}

